apiVersion: v1
kind: Namespace
metadata:
  name: tenant-2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: 
  name: tenant-2-admin
  namespace: fleet-system
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: tenant-2
  name: tenant-2-admin-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tenant-2-admin-binding
  namespace: tenant-2
subjects:
- kind: ServiceAccount
  name: tenant-2-admin
  namespace: fleet-system
  apiGroup: ""
roleRef:
  kind: Role
  name: tenant-2-admin-role
  apiGroup: ""
